# **Features Inside the Courtroom**

**Sources:**

Supreme Court Oral Arguments Corpus: https://convokit.cornell.edu/documentation/supreme.html

In [1]:
#install convokit
!pip install convokit

#import and download corpus
from convokit import Corpus, download
corpus = Corpus(filename=download("supreme-corpus"))

Collecting convokit
  Downloading convokit-4.1.0.tar.gz (240 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.9/240.9 kB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (3.10.0)
Requirement already satisfied: scipy>1.14 in /usr/local/lib/python3.12/dist-packages (from convokit) (1.16.3)
Requirement already satisfied: pandas>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (2.2.2)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (2.0.2)
Collecting msgpack-numpy>=0.4.3.2 (from convokit)
  Downloading msgpack_numpy-0.4.8-py2.py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: spacy>=3.8.2 in /usr/local/lib/python3.12/dist-packages (from convokit) (3.8.11)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (1.6.1)
Requirement already satisfied: nltk>=3.4 in /usr/local/lib/python3.12/dist-packages (from convokit) (3.9.1)
Requirement already satisfied: dill>=0.2.9 in /usr/local/lib/python3.12/dist-packages (from convokit) (0.3.8)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from convokit) (1.5.3)
Collecting clean-text>=0.6.0 (from convokit)
  Downloading clean_text-0.7.1-py3-none-any.whl.metadata (9.1 kB)
Collecting unidecode>=1.1.1 (from convokit)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (4.67.3)
Collecting pymongo>=4.0 (from convokit)
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Requirement already satisfied: pyyaml>=5.4.1 in /usr/local/lib/python3.12/dist-packages (from convokit) (6.0.3)
Collecting dnspython>=1.16.0 (from convokit)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: thinc<8.4.0,>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (8.3.10)
Collecting h5py==3.12.1 (from convokit)
  Downloading h5py-3.12.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Requirement already satisfied: numexpr>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (2.14.1)
Requirement already satisfied: ruff>=0.4.8 in /usr/local/lib/python3.12/dist-packages (from convokit) (0.15.5)
Requirement already satisfied: bottleneck in /usr/local/lib/python3.12/dist-packages (from convokit) (1.4.2)
Collecting evaluate (from convokit)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from convokit) (5.2.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from convokit) (4.0.0)
Collecting emoji>=2.1.0 (from clean-text>=0.6.0->convokit)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting ftfy<7.0,>=6.0 (from clean-text>=0.6.0->convokit)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (2.9.0.post0)
Requirement already satisfied: msgpack>=0.5.2 in /usr/local/lib/python3.12/dist-packages (from msgpack-numpy>=0.4.3.2->convokit) (1.1.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.4->convokit) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.4->convokit) (2025.11.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->convokit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->convokit) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->convokit) (3.6.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (3.0.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (0.24.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (75.2.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.0->convokit) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.0->convokit) (0.1.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (18.1.0)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (1.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->convokit) (5.0.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->convokit) (2.10.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->convokit) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (3.13.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy<7.0,>=6.0->clean-text>=0.6.0->convokit) (0.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets->convokit) (1.4.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets->convokit) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets->convokit) (0.24.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.8.2->convokit) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.8.2->convokit) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.8.2->convokit) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->convokit) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.8.2->convokit) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.8.2->convokit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.8.2->convokit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.8.2->convokit) (2026.2.25)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers->convokit) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers->convokit) (3.6.1)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->convokit) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->convokit) (0.7.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy>=3.8.2->convokit) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy>=3.8.2->convokit) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy>=3.8.2->convokit) (3.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets->convokit) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets->convokit) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets->convokit) (0.16.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy>=3.8.2->convokit) (2.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers->convokit) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets->convokit) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets->convokit) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets->convokit) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets->convokit) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets->convokit) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets->convokit) (0.1.2)
Downloading h5py-3.12.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 55.3 MB/s eta 0:00:00
Downloading clean_text-0.7.1-py3-none-any.whl (15 kB)
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 11.1 MB/s eta 0:00:00
Downloading msgpack_numpy-0.4.8-py2.py3-none-any.whl (6.9 kB)
Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 31.3 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 9.9 MB/s eta 0:00:00
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.7 MB/s eta 0:00:00
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 19.4 MB/s eta 0:00:00
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.3 MB/s eta 0:00:00
Building wheels for collected packages: convokit
  Building wheel for convokit (pyproject.toml) ... done
  Created wheel for convokit: filename=convokit-4.1.0-py3-none-any.whl size=292185 sha256=61b79d3f83fa8baf8e7f158c967757e0dde522b4ccbb52acdca67a75ef360b29
  Stored in directory: /root/.cache/pip/wheels/5e/d8/32/b867fe29313972bfba4cb57051565bd1395d7561df03839b5e
Successfully built convokit
Installing collected packages: unidecode, msgpack-numpy, h5py, ftfy, emoji, dnspython, pymongo, clean-text, evaluate, convokit
  Attempting uninstall: h5py
    Found existing installation: h5py 3.16.0
    Uninstalling h5py-3.16.0:
      Successfully uninstalled h5py-3.16.0
Successfully installed clean-text-0.7.1 convokit-4.1.0 dnspython-2.8.0 emoji-2.15.0 evaluate-0.4.6 ftfy-6.3.1 h5py-3.12.1 msgpack-numpy-0.4.8 pymongo-4.16.0 unidecode-1.4.0
No configuration file found at /root/.convokit/config.yml; writing with contents:
# Default Backend Parameters
db_host: localhost:27017
data_directory: ~/.convokit/saved-corpora
model_directory: ~/.convokit/saved-models
default_backend: mem
Downloading supreme-corpus to /root/.convokit/saved-corpora/supreme-corpus
Downloading supreme-corpus from http://zissou.infosci.cornell.edu/convokit/datasets/supreme-corpus/supreme-corpus.zip (1255.8MB)... Done

In [2]:
import pandas as pd
cases_df = pd.read_json("https://zissou.infosci.cornell.edu/convokit/datasets/supreme-corpus/cases.jsonl", lines=True)
cases_df.head()

,id,year,citation,title,petitioner,respondent,docket_no,court,decided_date,url,...,adv_sides_inferred,known_respondent_adv,advocates,win_side,win_side_detail,scdb_docket_id,votes,votes_detail,is_eq_divided,votes_side
0,1955_71,1955,350 US 79,Affronti v. United States,Affronti,United States,71,Warren Court,"Dec 5, 1955",https://www.oyez.org/cases/1955/71,...,True,True,"{'Harry F. Murphy': {'id': 'harry_f_murphy', '...",0.0,2.0,1955-009-01,"{'j__john_m_harlan2': 2.0, 'j__hugo_l_black': ...","{'j__john_m_harlan2': 1.0, 'j__hugo_l_black': ...",0.0,"{'j__john_m_harlan2': 0.0, 'j__hugo_l_black': ..."
1,1955_410,1955,351 US 79,"American Airlines, Inc. v. North American Airl...","American Airlines, Inc.","North American Airlines, Inc.",410,Warren Court,"Apr 23, 1956",https://www.oyez.org/cases/1955/410,...,True,True,{'Howard C. Westwood': {'id': 'howard_c_westwo...,1.0,4.0,1955-071-01,"{'j__john_m_harlan2': 2.0, 'j__hugo_l_black': ...","{'j__john_m_harlan2': 1.0, 'j__hugo_l_black': ...",0.0,"{'j__john_m_harlan2': 1.0, 'j__hugo_l_black': ..."
2,1955_351,1955,350 US 532,Archawski v. Hanioti,Archawski,Hanioti,351,Warren Court,"Apr 9, 1956",https://www.oyez.org/cases/1955/351,...,True,False,"{'Harry D. Graham': {'id': 'harry_d_graham', '...",1.0,4.0,1955-053-01,"{'j__john_m_harlan2': 2.0, 'j__hugo_l_black': ...","{'j__john_m_harlan2': 1.0, 'j__hugo_l_black': ...",0.0,"{'j__john_m_harlan2': 1.0, 'j__hugo_l_black': ..."
3,1955_38,1955,350 US 568,Armstrong v. Armstrong,Armstrong,Armstrong,38,Warren Court,"Apr 9, 1956",https://www.oyez.org/cases/1955/38,...,True,False,"{'Robert N. Gorman': {'id': 'robert_n_gorman',...",0.0,2.0,1955-056-01,"{'j__john_m_harlan2': 2.0, 'j__hugo_l_black': ...","{'j__john_m_harlan2': 1.0, 'j__hugo_l_black': ...",0.0,"{'j__john_m_harlan2': 0.0, 'j__hugo_l_black': ..."
4,1955_49,1955,350 US 198,"Bernhardt v. Polygraphic Company of America, Inc.",Bernhardt,"Polygraphic Company of America, Inc.",49,Warren Court,"Jan 16, 1956",https://www.oyez.org/cases/1955/49,...,True,False,"{'Manfred W. Ehrich, Jr.': {'id': 'manfred_w_e...",1.0,4.0,1955-020-01,"{'j__john_m_harlan2': 1.0, 'j__hugo_l_black': ...","{'j__john_m_harlan2': 2.0, 'j__hugo_l_black': ...",0.0,"{'j__john_m_harlan2': 0.0, 'j__hugo_l_black': ..."

**Separate components of corpus:**
- Utterances
- Converstions
- Speakers

In [3]:
#UTTERANCES
utterances_df = corpus.get_utterances_dataframe()
utterances_df.head()

,timestamp,text,speaker,reply_to,conversation_id,meta.case_id,meta.start_times,meta.stop_times,meta.speaker_type,meta.side,meta.timestamp,vectors
id,,,,,,,,,,,,
13127__0_000,None,"Number 71, Lonnie Affronti versus United State...",j__earl_warren,None,13127,1955_71,"[0.0, 7.624]","[7.624, 9.218]",J,None,0.0,[]
13127__0_001,None,May it please the Court.\nWe are here by writ ...,harry_f_murphy,13127__0_000,13127,1955_71,"[9.218, 11.538, 15.653, 22.722, 28.849, 33.575]","[11.538, 15.653, 22.722, 28.849, 33.575, 48.138]",A,1,9.218,[]
13127__0_002,None,Consecutive sentences.,j__william_o_douglas,13127__0_001,13127,1955_71,[48.138],[49.315],J,None,48.138,[]
13127__0_003,None,"Consecutive sentences.\nIn this case, the defe...",harry_f_murphy,13127__0_002,13127,1955_71,"[49.315, 51.844, 60.81, 67.083, 72.584, 89.839...","[51.844, 60.81, 67.083, 72.584, 89.839, 95.873...",A,1,49.315,[]
13127__0_004,None,Was the aggregate prison sentence was 20 or 25...,<INAUDIBLE>,13127__0_003,13127,1955_71,[174.058],[176.766],None,None,174.058,[]

In [4]:
#CONVERSATIONS
conversations_df = corpus.get_conversations_dataframe()
conversations_df.head()

,vectors,meta.case_id,meta.advocates,meta.win_side,meta.votes_side
id,,,,,
13127,[],1955_71,"{'harry_f_murphy': {'side': 1, 'role': 'inferr...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,..."
12997,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,..."
13024,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,..."
13015,[],1955_351,"{'harry_d_graham': {'side': 3, 'role': 'inferr...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,..."
13016,[],1955_38,"{'robert_n_gorman': {'side': 3, 'role': 'infer...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,..."

In [5]:
#SPEAKERS
speakers_df = corpus.get_speakers_dataframe()
speakers_df.head()

                     vectors           meta.name meta.type  meta.role
id
j__earl_warren            []         Earl Warren         J    justice
harry_f_murphy            []     Harry F. Murphy         A        NaN
j__william_o_douglas      []  William O. Douglas         J    justice
<INAUDIBLE>               []         <INAUDIBLE>         U  inaudible
j__felix_frankfurter      []   Felix Frankfurter         J    justice

**Analysis:**
Winning vs Losing side features:
- Sentiment Score
- Lawyer Response Length to Justice's Questions
- Citing precedent

In [6]:
#winning side distribution
print(utterances_df["meta.side"].value_counts())
print(utterances_df["meta.speaker_type"].value_counts())

meta.side
1    341431
0    305071
3    154335
2     24432
Name: count, dtype: int64
meta.speaker_type
A    825269
J    787417
Name: count, dtype: int64

In [7]:
conversations_df["meta.win_side"].value_counts()

meta.win_side
1     4930
0     2868
2        4
-1       2
Name: count, dtype: int64

*Interpretation*

---



1= how many cases were won by the petitioner (4930)

0= how many cases were won by the respondent (2868)

-1= how many cases have no winner information (2)

In [8]:
#get all the advocate utterances and save them as their own separate dataframe
advocate_utterances = utterances_df[utterances_df["meta.speaker_type"] == "A"].copy()

#look up winning side for each utterance based on which conversation it came from
advocate_utterances = advocate_utterances.merge(
    conversations_df[["meta.win_side"]],
    left_on="conversation_id",
    right_index=True,
    how="left"
)

advocate_utterances.head()

,timestamp,text,speaker,reply_to,conversation_id,meta.case_id,meta.start_times,meta.stop_times,meta.speaker_type,meta.side,meta.timestamp,vectors,meta.win_side
id,,,,,,,,,,,,,
13127__0_001,None,May it please the Court.\nWe are here by writ ...,harry_f_murphy,13127__0_000,13127,1955_71,"[9.218, 11.538, 15.653, 22.722, 28.849, 33.575]","[11.538, 15.653, 22.722, 28.849, 33.575, 48.138]",A,1,9.218,[],0
13127__0_003,None,"Consecutive sentences.\nIn this case, the defe...",harry_f_murphy,13127__0_002,13127,1955_71,"[49.315, 51.844, 60.81, 67.083, 72.584, 89.839...","[51.844, 60.81, 67.083, 72.584, 89.839, 95.873...",A,1,49.315,[],0
13127__0_005,None,Twenty years.,harry_f_murphy,13127__0_004,13127,1955_71,[176.766],[177.525],A,1,176.766,[],0
13127__0_007,None,"Twenty years, four -- four counts of five year...",harry_f_murphy,13127__0_006,13127,1955_71,"[177.844, 183.613, 204.06, 225.112, 253.196, 2...","[183.613, 204.06, 225.112, 253.196, 268.426, 2...",A,1,177.844,[],0
13127__0_009,None,"Well the -- the probation statute, I think, wh...",harry_f_murphy,13127__0_008,13127,1955_71,[566.261],[576.08],A,1,566.261,[],0

*Interpretation*


---


advocate_utterances:
has all the advocate speech, but doesn't know who won


conversations_df[["meta.win_side"]]:
has the winning side information for each conversation


The merge connects them by matching conversation_id in advocate_utterances (every utterance knows which conversation it belongs to) with the index of conversations_df (which is the conversation ID). So after the merge, every advocate utterance will have a new column meta.win_side telling us who won that case. Left merge keeps all the advocate utterances even if no match is found.

In [9]:
#create won column
advocate_utterances["won"] = (
    advocate_utterances["meta.side"] == advocate_utterances["meta.win_side"]
).astype(int)

#drop -1 cases
advocate_utterances = advocate_utterances[advocate_utterances["meta.win_side"] != -1]

advocate_utterances["won"].value_counts()

won
0    514974
1    310202
Name: count, dtype: int64

*Interpretation*


---



advocate_utterances["meta.side"]:
tells which side the advocate is on (1 for petitioner, 0 for respondent)

advocate_utterances["meta.win_side"]:
tells us which side won the case (1 for petitioner, 0 for respondent)


- So if an advocate is on side 1 and the winning side is 1, they match and the advocate won.

- If an advocate is on side 0 and the winning side is 1, they don't match and the advocate lost.

- The comparison gives us 1's or 0's indicating whether an advocate was on the winning side (1) or on the losing side (0).

In [17]:
#average sentiment scores for winning vs losing advocates
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

# get sentiment score for each utterance
sentiments = []
for text in advocate_utterances["text"]:
    #compound = VADER's overall sentiment score for a piece of text, a single number between -1.0 and +1.0
    score = sia.polarity_scores(str(text))["compound"]
    sentiments.append(score)

advocate_utterances.loc[:, "sentiment"] = sentiments

advocate_utterances.groupby("won")["sentiment"].mean()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

won
0    0.175560
1    0.178376
Name: sentiment, dtype: float64

**Findings:**

Sentiment scores are nearly identical between winning and losing advocates which suggests that positivity of language is not a distinguishing factor in Supreme Court oral arguments. Therefore, word choice matters more than tone.

In [21]:
import plotly.express as px

sentiment_means = advocate_utterances.groupby("won")["sentiment"].mean().reset_index()
sentiment_means["outcome"] = ["Losing", "Winning"]

fig = px.bar(sentiment_means, x="outcome", y="sentiment",
             color="outcome",
             color_discrete_map={"Losing": "lightskyblue", "Winning": "#5B2D8E"},
             title="Average Sentiment Score by Outcome",
             labels={"sentiment": "Average Sentiment Score", "outcome": ""})

fig.update_layout(showlegend=False)

#update bar properties to display the sentiment to the 4th decimal
fig.update_traces(texttemplate="%{y:.4f}", textposition="outside")
fig.show()

In [23]:
advocate_utterances["year"] = advocate_utterances["meta.case_id"].str.split("_").str[0].astype(int)
advocate_utterances["decade"] = (advocate_utterances["year"] // 10) * 10
advocate_utterances["won_label"] = advocate_utterances["won"].map({0: "Losing", 1: "Winning"})

sentiment_by_decade = advocate_utterances.groupby(["decade", "won_label"])["sentiment"].mean().reset_index()

fig = px.line(sentiment_by_decade, x="decade", y="sentiment",
              color="won_label",
              markers=True,
              color_discrete_map={"Losing": "lightskyblue", "Winning": "#5B2D8E"},
              title="Average Sentiment Score by Decade and Outcome",
              labels={"sentiment": "Average Sentiment Score", "decade": "Decade", "won_label": ""})

fig.update_layout(width=1500)
fig.show()

In [11]:
#winning advocate response length
response_lengths = []
for text in advocate_utterances["text"]:
    #split on white space
    length = len(str(text).split())
    response_lengths.append(length)

#get all rows and one column
advocate_utterances.loc[:, "response_length"] = response_lengths

#get justice utterance IDs
justice_ids = set(utterances_df[utterances_df["meta.speaker_type"] == "J"].index)

#filter to advocate utterances that are replying to a justice
responses_to_justices = advocate_utterances[
    advocate_utterances["reply_to"].isin(justice_ids)
]

responses_to_justices.groupby("won")["response_length"].mean()

won
0    60.791526
1    65.736386
Name: response_length, dtype: float64

**Findings:**

Winning advocates tend to give longer responses to justice questions on average (65 words) compared to losing advocates (60 words).

In [24]:
response_means = advocate_utterances.groupby("won")["response_length"].mean().reset_index()
response_means["outcome"] = ["Losing", "Winning"]

fig = px.bar(response_means, x="response_length", y="outcome",
             orientation="h",
             color="outcome",
             color_discrete_map={"Losing": "lightskyblue", "Winning": "#5B2D8E"},
             title="Average Response Length by Outcome",
             labels={"response_length": "Average Words per Question", "outcome": ""})

fig.update_traces(texttemplate="%{x:.1f}", textposition="outside")
fig.update_layout(showlegend=False, width=1500)
fig.show()

In [14]:
#citing precedent average
citation_counts = []

for text in advocate_utterances["text"]:
    text = str(text).lower()
    count = text.count(" v. ")
    citation_counts.append(count)

advocate_utterances["citation_count"] = citation_counts
advocate_utterances["citation_rate"] = advocate_utterances["citation_count"] / advocate_utterances["response_length"]

advocate_utterances.groupby("won")["citation_rate"].mean()

won
0    0.000240
1    0.000298
Name: citation_rate, dtype: float64

In [15]:
from scipy import stats

winning = advocate_utterances[advocate_utterances["won"] == 1]["citation_rate"]
losing = advocate_utterances[advocate_utterances["won"] == 0]["citation_rate"]

stats.ttest_ind(winning, losing)

TtestResult(statistic=np.float64(6.385889623946161), pvalue=np.float64(1.704939241771275e-10), df=np.float64(825174.0))

**Findings:**

The results show winning advocates cite slightly more per word (0.000298) than losing ones (0.000240), though the difference is very small. After doing a t-test to verify that the difference is indeed statistically significant, the difference is too small to conclude much. Lawyers on the winning side do use a bit more precedent, but not much.

In [25]:
citation_means = advocate_utterances.groupby("won")["citation_rate"].mean().reset_index()
citation_means["outcome"] = ["Losing", "Winning"]

fig = px.bar(citation_means, x="outcome", y="citation_rate",
             color="outcome",
             color_discrete_map={"Losing": "lightskyblue", "Winning": "#5B2D8E"},
             title="Average Citation Rate by Outcome",
             labels={"citation_rate": "Average Citation Rate", "outcome": ""})

fig.update_traces(texttemplate="%{y:.6f}", textposition="outside")
fig.update_layout(showlegend=False)
fig.show()

In [26]:
#create new dataframe with average citation rate for each decade and outcome combination
citation_by_decade = advocate_utterances.groupby(["decade", "won_label"])["citation_rate"].mean().reset_index()
fig = px.line(citation_by_decade, x="decade",
              y="citation_rate",
              color="won_label",
              markers=True,
              color_discrete_map={"Losing": "lightskyblue", "Winning": "#5B2D8E"},
              title="Average Citation Rate by Decade and Outcome",
              labels={"citation_rate": "Average Citation Rate", "decade": "Decade", "won_label": ""})

fig.update_layout(width=1500)
fig.show()

**Analysis:**

Logistic Regression Model to predict whether a lawyer will win or lose based on stretegic features

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

#make one row per advocate per case
features = advocate_utterances.groupby(["speaker", "meta.case_id", "won"]).agg(
    sentiment=("sentiment", "mean"),
    response_length=("response_length", "mean"),
    citation_rate=("citation_rate", "mean"),
).reset_index()

features = features.dropna(subset=["sentiment", "response_length", "citation_rate"])

X_all = features[["sentiment", "response_length", "citation_rate"]]
y_all = features["won"]

scores = cross_val_score(LogisticRegression(class_weight="balanced"),
                         X_all,
                         y_all,
                         cv=5,
                         scoring="accuracy")

#mean accuracy of all features combined
print("Mean accuracy: " + str(scores.mean().round(3)))

Mean accuracy: 0.514

*Interpretation:*


---

The model correctly predicted whether an advocate won or lost 51.4% of the time. This is only slightly better than randomly guessing (50%), so these features are not the strongest predicters of win rate.

In [28]:
features_list = ["sentiment", "response_length", "citation_rate"]

#loop through each feature
for feature in features_list:
    X_one = features[[feature]]
    y_one = features["won"]

    scores = cross_val_score(LogisticRegression(class_weight="balanced"),
                             X_one,
                             y_one,
                             cv=5,
                             scoring="accuracy")

    print(feature + ":")
    print("  Mean accuracy: " + str(scores.mean().round(3)))
    print("  Std: " + str(scores.std().round(3)))
    print()

sentiment:
  Mean accuracy: 0.497
  Std: 0.015

response_length:
  Mean accuracy: 0.512
  Std: 0.07

citation_rate:
  Mean accuracy: 0.613
  Std: 0.0

*Interpretation:*


---

- Sentiment had a 49.7% accuracy rate which is literally worse than random guessing, so there is no predictive power at all.

- Response length had a 51.2% accuracy which is barely above randomly guessing, also suggesting a very weak signal. The high standard deviation on response length (0.07) is also worth noting, because it is very inconsistent across folds, meaning it performs well on some splits and poorly on others, which suggests it's not a reliable predictor.

- Citation rate, on the other hand, had a 61.3% accuracy, which is the highest of the three, meaning that it is the stongest predictor of win rate.


Conclusion:
Advocates who cite more case law are more likely to win.

In [29]:
import plotly.express as px

df = pd.DataFrame({
    "feature": ["Sentiment", "Response Length", "Citation Rate"],
    "accuracy": [0.497, 0.512, 0.613]
})

fig = px.bar(df,
             x="accuracy",
             y="feature",
             color="feature",
             color_discrete_map={
                 "Sentiment": "#C9B8E8",
                 "Response Length": "#9B6FD4",
                 "Citation Rate": "#5B2D8E"
             },
             title="Predictive Accuracy by Feature",
             labels={"accuracy": "Mean Accuracy", "feature": ""})

fig.add_vline(x=0.5, line_dash="dash", annotation_text="Random baseline")
fig.update_layout(showlegend=False, height= 700, width= 1300, xaxis=dict(range=[0, 0.65]))
fig.show()

In [30]:
X_two = features[["response_length", "citation_rate"]]

scores = cross_val_score(LogisticRegression(class_weight="balanced"),
                         X_two,
                         y_all,
                         cv=5,
                         scoring="accuracy")

print("Mean accuracy: " + str(scores.mean().round(3)))
print("Std: " + str(scores.std().round(3)))

Mean accuracy: 0.512
Std: 0.07

**Findings:**

Citation rate is the strongest signal, and combining it with response length only introduces noise